# @package _group_
data_root_dir: /workspace/image-inpainting-research/data/places365_building
out_root_dir: /workspace/image-inpainting-research/outputs/train_runs
tb_dir: /workspace/image-inpainting-research/outputs/tb_logs
pretrained_models: /workspace/image-inpainting-research
